### ISSUE TITLE
Lasers mysteriously turn off when activating a catcher

### ISSUE THREAD

**Issue by vrad-exe** [ZeroNoFun/Gmod-Aperture-science-laboratories#13]
If a laser is set to start enabled and activates a catcher or relay, the laser will mysteriously turn off, even though it's not connected to the catcher in any way. Because the catcher is no longer activated, the laser will turn back on and reactivate the catcher, causing an infinite loop. To work around this issue, I tried connecting a wiremod NOT gate to a laser set to start disabled. However, that simply caused the opposite to happen - once the catcher stops getting activated, the laser turns off, meaning it can't be reactivated because there's no more laser. Even weirder, if a pellet catcher is activated that will *also* turn off the laser! This is a *very* strange bug which I hope will be fixed soon.

**Comment by vrad-exe** [comment]
Alright...so, this issue doesn't just apply to lasers - when anything that generates outputs is activated, everything that accepts inputs toggles its state, even if they're not connected or even anywhere near each other. This definitely needs to be fixed soon, it makes it pretty much impossible to make anything using the Portal test elements.

**Comment by vrad-exe** [comment]
I did more testing and found that this does *not* happen if Wiremod is disabled/not installed. That makes me think this might be a bug with Wiremod that has nothing to do with this addon.

**Comment by vrad-exe** [comment]
Or...maybe it still does? Now all of a sudden the bug is happening again, and I'm using the same items as last time. Strange!

**Comment by francodml** [comment]
This is caused by the keyboard button trigger, simply change the key in the tool's options to not match activator ones. Setting it to NONE (right clicking) won't work because the code still checks for when the NONE key (described as 0 in code) is pressed

**Comment by vrad-exe** [comment]
Oh, so is this intentional after all?

**Comment by francodml** [comment]
Yeah, it's actually the intended behaviour. I had it happen to me too cause I hadn't realised a laser relay was simulating the numpad 8 key and the laser emitter was toggled with the same key

**Comment by vrad-exe** [comment]
I just set all the input-accepting items to NONE and the outputting items to numpad 8, and now I don't have the issue.
