### ISSUE TITLE
Very buggy things

### ISSUE THREAD

**Issue by Levi84** [ZeroNoFun/Gmod-Aperture-science-laboratories#16]
There is lots of buggy stuff about this addon for me, for example, Some of the little icons for the model selecting in the right menu, some of the images are corrupted garbage, and there are some glitches with other things too, like Pneumatic Diversity Vents are glitchy, they dont have an undo for the tubes, only the start area, and those Discouragement field and Material Emancipation grill wont start, even with numpad keys, and the other side stays after undoing, so idk.

I can add images/gifs if you'd like, or even videos

**Comment by Levi84** [comment]
https://youtu.be/vNPs67hCbHY
here's your video :P

**Comment by ZeroNoFun** [comment]
About this video. You trying to connect button input to 'Material Emancipation Grid' output(there's 0) , or what? About the other things i will look into that and try to fix. ty for report.

**Comment by Levi84** [comment]
Well i can't start the with the MEG wiring, i can only start with the button :/
